# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name = "About"
#  url = "#about"
#  weight = 10
#
#[[main]]
#  name = "Guide"
#  url = "https://stat545guidebook.netlify.com"
#  weight = 20
#
#[[main]]
#  name = "Structure"
#  url = "#structure"
#  weight = 25
#
#[[main]]
#  name = "Evaluation"
#  url = "#evaluation"
#  weight = 30
#
#[[main]]
#  name = "Teaching Team"
#  url = "#team"
#  weight = 50
#
#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60
#
#[[main]]
#  name = "Resources"
#  url = "#resources"
#  weight = 70


