language: r
sudo: false
cache: packages

before_install:
- npm install netlify-cli -g

script:
- Rscript -e 'rmarkdown::render_site()'

after_success:
- netlify deploy --prod --dir docs

deploy:
  provider: script
  script: netlify deploy --dir docs --prod --message "$DEPLOY_MSG"
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master

# Thanks, https://github.com/rstudio-education/stat545-reboot/issues/1
